<?php

/**
 * Implements hook_theme().
 */
function layout_entity_theme() {
  $theme = [];
  $theme['layout_entity'] = [
    'render element' => 'elements',
    'file' => 'layout_entity.page.inc',
    'template' => 'layout_entity',
  ];
  $theme['layout_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'layout_entity.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function layout_entity_theme_suggestions_layout_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#layout_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'layout_entity__' . $sanitized_view_mode;
  $suggestions[] = 'layout_entity__' . $entity->bundle();
  $suggestions[] = 'layout_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'layout_entity__' . $entity->id();
  $suggestions[] = 'layout_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
